### PR TITLE
Fixes issues with vagrant startup.  

### PR DESCRIPTION
**Pull request by halfak**
1. Virtualbox won't try to use USB -- no good reason we need that.

### CODE REVIEW

**Comment by halfak** [comment]
@adamwight, could you take a look at this one?

**Comment by adamwight** [comment]
So far, I'm getting success on the first `vagrant up`, using the master branch.

There are some errors compiling numpy, "libyaml is not found" it looks bad but it's not causing the overall provisioning to fail, so I guess that's recoverable.

Can you explain what problem this is fixing?  Have any error messages to paste here?

**Comment by adamwight** [comment]
Looks helpful, merging!

I was unable to reproduce the bug fixed here.

**Comment by halfak** [comment]
Sorry for the delay, here's the error message I got from Vbox:

```
Failed to open a session for the virtual machine .... Implementation of the USB 2.0 controller not found! Because the USB 2.0 controller state is part of the saved VM state, the VM cannot be started. To fix this problem, either install the 'Oracle VM VirtualBox Extension Pack' or disable USB 2.0 support in the VM settings (VERR_NOT_FOUND). Unknown error creating VM (VERR_NOT_FOUND).
```

This is remedied by installing the 'Oracle VM VirtualBox Extension Pack', but I thought it was a better idea to just disable USB 2.0 support.

**Comment by adamwight** [comment]
Ah, that makes sense, thanks for finding a workaround!  Yeah, I had the extension pack enabled already therefore didn't experience the error, but it's not installed by default.

**Comment by halfak** [comment]
@adamwight  merge-y?

**Comment by adamwight** [comment]
Hah,
> Pull requests that have a failing status can’t be merged from a phone.

Whoops, gimme a few minutes. Thought I had already merged this!

**Comment by adamwight** [comment]
Hah,
> Pull requests that have a failing status can’t be merged from a phone.

Whoops, gimme a few minutes. Thought I had already merged this!

**Pull request merged**
