### PR TITLE
Ship Wikimedia UI and its dependency (bootstrap)

### PR DESCRIPTION
**Pull request by Ladsgroup**

### CODE REVIEW

**Comment by Ladsgroup** [comment]
I haven't tested it (yet)

**Comment by halfak** [comment]
PSA: Do not clik on the "Files changed" link above :)   I did and it locked up my computer.

**Comment by Ladsgroup** [comment]
https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=PSA+meaning

In order to prevent LOLs in the future PSA stands for "public service announcement"

**Comment by halfak** [comment]
This change was addressed in https://github.com/wiki-ai/ores/pull/149

**Pull request closed without merging**
