### PR TITLE
Adds support for metrics collection

### PR DESCRIPTION
**Pull request by halfak**

### CODE REVIEW

**Comment by ToAruShiroiNeko** [comment]
I think it would be useful to take model version number in to account when generating statistics. We can use those as cut off points or defacto milestones.

**Comment by ToAruShiroiNeko** [comment]
-  score_processor: local_celery
+  score_processor: local_timeout

What ıs the reason for this change? I do not uite understand it.

Aside from that it looks good to me.

**Comment by halfak** [comment]
@ToAruShiroiNeko good idea.  Versions are now recorded.  

Regarding the change from local_celery to local_timeout, that makes setting up the dev server a little easier because you don't need a celery worker instance to run it.  I used that in testing to make sure we were logging metrics correctly.

**Comment by halfak** [comment]
Fixes https://github.com/wiki-ai/ores/issues/94

**Pull request merged**
